<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Datos Personales</title>
	<style type="text/css">
	body{
			background: black;
			font-family: sans-serif;
				font-size: 20px;
}
</style>
</head>
<body>
<?php
	echo 'Nombre: Alejandro Nicolás González Gurrola<p>
			
			Nacimiento: 03/12/2008<p>

			Gustos Personales: <pre> 1. Escuchar musica. <pre> 2. Jugar videojuegos. <pre> 3. Leer. <pre> 4. Tocar la guitarra. <pre> 5. Jugar con mi perro.'
?>
</body>
</html>